"""Tests for the external PointNXT authentication bridge."""

import asyncio
import base64
import hashlib
import re
import sqlite3
import time
from unittest.mock import patch
from urllib.parse import parse_qs, urlencode, urlsplit

from services import auth_bridge, mcp_oauth, session_store
from services.auth_session import set_session
from services.request_context import get_request_key, reset_request_key, set_request_key


class Request:
    def __init__(
        self, query="", body="", method="GET", client_host="127.0.0.1", scheme="https"
    ):
        self.query_params = {
            key: values[0] for key, values in parse_qs(query).items()
        }
        self._body = body.encode()
        self.method = method
        self.headers = {"content-length": str(len(self._body))} if body else {}
        self.client = type("Client", (), {"host": client_host})()
        self.url = type("URL", (), {"scheme": scheme})()

    async def body(self):
        return self._body

    async def stream(self):
        yield self._body


def verifier_pair():
    verifier = "v" * 64
    challenge = base64.urlsafe_b64encode(
        hashlib.sha256(verifier.encode()).digest()
    ).rstrip(b"=").decode()
    return verifier, challenge


async def main() -> None:
    session_store.clear_all_for_tests()
    old_client = mcp_oauth.MCP_OAUTH_CLIENT_ID
    old_redirect = mcp_oauth.MCP_OAUTH_REDIRECT_URI
    mcp_oauth.MCP_OAUTH_CLIENT_ID = "bridge-client"
    mcp_oauth.MCP_OAUTH_REDIRECT_URI = "https://client.example/callback"
    verifier, challenge = verifier_pair()

    query = urlencode(
        {
            "client_id": "bridge-client",
            "redirect_uri": "https://client.example/callback",
            "state": "bridge-state",
            "code_challenge": challenge,
            "code_challenge_method": "S256",
            "scope": "mcp",
            "resource": mcp_oauth.MCP_RESOURCE,
        }
    )
    try:
        authorize_response = await mcp_oauth.authorize(Request(query))
        assert authorize_response.status_code == 302
        login_location = authorize_response.headers["location"]
        assert urlsplit(login_location).path == "/auth/login"
        assert "PointNXT" not in login_location

        login_response = await auth_bridge.login_page(
            Request("state=bridge-state")
        )
        assert login_response.status_code == 200
        for header, value in {
            "content-security-policy": "form-action 'self'",
            "x-frame-options": "DENY",
            "x-content-type-options": "nosniff",
            "referrer-policy": "no-referrer",
            "cache-control": "no-store",
        }.items():
            assert login_response.headers[header] == value or value in login_response.headers[header]
        form = login_response.body.decode()
        nonce = re.search(r'name="nonce" value="([^"]+)"', form).group(1)

        async def fake_login(email, password, remember_device=True):
            assert email == "alice@example.com"
            assert password == "not-logged"
            assert remember_device is True
            assert get_request_key().startswith("oauth:")
            set_session(
                {
                    "data": {
                        "accessToken": "server-only-access",
                        "refreshToken": "server-only-refresh",
                        "tenantId": "tenant-a",
                        "userId": "user-a",
                        "membershipId": "membership-a",
                    }
                }
            )
            return {"authenticated": True}

        # The exact transaction key is generated by the authorization handler;
        # the callback verifies it against the stored transaction, so the mock
        # only checks that a transaction-scoped key is used.
        with patch("tools.auth.login_with_credentials", new=fake_login):
            submit = await auth_bridge.login_submit(
                Request(
                    method="POST",
                    body=urlencode(
                        {
                            "state": "bridge-state",
                            "nonce": nonce,
                            "email": "alice@example.com",
                            "password": "not-logged",
                        }
                    ),
                )
            )
        assert submit.status_code == 303
        callback_location = submit.headers["location"]
        assert "code=" not in callback_location
        callback_query = parse_qs(urlsplit(callback_location).query)
        assert callback_query["bridge"] == ["1"]

        callback = await mcp_oauth.callback(
            Request(
                urlencode(
                    {
                        "state": "bridge-state",
                        "bridge": "1",
                    }
                )
            )
        )
        assert callback.status_code == 302
        code = parse_qs(urlsplit(callback.headers["location"]).query)["code"][0]
        token = await mcp_oauth.token(
            Request(
                method="POST",
                body=urlencode(
                    {
                        "grant_type": "authorization_code",
                        "client_id": "bridge-client",
                        "redirect_uri": "https://client.example/callback",
                        "resource": mcp_oauth.MCP_RESOURCE,
                        "code_verifier": verifier,
                        "code": code,
                    }
                ),
            )
        )
        assert token.status_code == 200
        assert b"server-only-access" not in token.body
        assert b"server-only-refresh" not in token.body
        with sqlite3.connect(session_store._path) as connection:
            payloads = [row[0] for row in connection.execute("SELECT payload FROM sessions")]
        assert payloads and all(payload.startswith("enc:v1:") for payload in payloads)
        assert all("server-only-access" not in payload for payload in payloads)
        assert all("server-only-refresh" not in payload for payload in payloads)

        replay = await auth_bridge.callback(
            Request("state=bridge-state&bridge=1")
        )
        assert replay.status_code == 400

        # A bridge claim is atomic: exactly one concurrent claimant wins.
        session_store.put_auth_bridge_transaction(
            "race-state", "race-session", {}, time.time() + 60
        )
        assert session_store.set_auth_bridge_nonce("race-state", "race-nonce")
        claims = await asyncio.gather(
            asyncio.to_thread(
                session_store.claim_auth_bridge_transaction, "race-state", "race-nonce"
            ),
            asyncio.to_thread(
                session_store.claim_auth_bridge_transaction, "race-state", "race-nonce"
            ),
        )
        assert sum(claim is not None for claim in claims) == 1

        # Expired and wrong/replayed nonces never claim a transaction.
        session_store.put_auth_bridge_transaction(
            "expired-state", "expired-session", {}, time.time() - 1
        )
        assert not session_store.set_auth_bridge_nonce("expired-state", "nonce")
        assert session_store.claim_auth_bridge_transaction("expired-state", "nonce") is None
        session_store.put_auth_bridge_transaction(
            "nonce-state", "nonce-session", {}, time.time() + 60
        )
        assert session_store.set_auth_bridge_nonce("nonce-state", "good-nonce")
        assert session_store.claim_auth_bridge_transaction("nonce-state", "wrong") is None
        assert session_store.claim_auth_bridge_transaction("nonce-state", "good-nonce")
        assert session_store.claim_auth_bridge_transaction("nonce-state", "good-nonce") is None

        session_store.clear_all_for_tests()
        assert session_store.consume_rate_limit("test-ip", 2, 300)
        assert session_store.consume_rate_limit("test-ip", 2, 300)
        assert not session_store.consume_rate_limit("test-ip", 2, 300)

        # Oversized and malformed requests are rejected before authentication.
        oversized = await auth_bridge.login_submit(Request(body="x" * (16 * 1024 + 1), method="POST"))
        assert oversized.status_code == 400
        malformed = await auth_bridge.login_submit(Request(body="%FF", method="POST"))
        assert malformed.status_code == 400

        # DEV_MODE never enables the local callback path for an HTTP request.
        with patch("tools.auth.DEV_MODE", True), patch(
            "tools.auth._wait_for_callback", side_effect=AssertionError("must not open browser")
        ):
            token = set_request_key("http-session")
            try:
                dev_result = await __import__("tools.auth", fromlist=["authenticate"]).authenticate()
            finally:
                reset_request_key(token)
        assert dev_result["authenticated"] is False
        assert "disabled" in dev_result["message"]
    finally:
        mcp_oauth.MCP_OAUTH_CLIENT_ID = old_client
        mcp_oauth.MCP_OAUTH_REDIRECT_URI = old_redirect
        session_store.clear_all_for_tests()
        reset_request_key(set_request_key(None))

    print("Authentication bridge tests passed")


if __name__ == "__main__":
    asyncio.run(main())
